### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by lxwulf** [iamgio/quarkdown#4]
Hello there 👋,

I'm very interested in this project! I want to give this a try, but the lack of documentation makes it hard, at least for me. Likewise, I may miss something. 🤷‍♂️

What I have in mind is something like a [cheat sheet](https://www.markdownguide.org/cheat-sheet/) or of course something like [this](https://www.markdownguide.org/basic-syntax/) with more details.

I know there is `demo code` from the demo website, but still it's hard to filter out what is needed for my idea or document. 

I may be wrong with the expectation of this project, but I wanted to replace my momentary working tools with `quarkdown`.

PS: What about export to `PDF`?

Else great idea and work! 👏

**Comment by iamgio** [comment]
Hi @lxwulf and thank you for your appreciation towards the project! As Quarkdown gets closer to a stable version commit by commit, I myself notice how important it is to have documentation available, and that's why doing something like what you mentioned is at the top of my list.

However, even if there is not a "unified" documentation yet, here are some useful resources:
- [README](https://github.com/iamgio/quarkdown/blob/main/README.md#installation) for installation and getting started;
- [Wiki](https://github.com/iamgio/quarkdown/wiki) ~which is currently work in progress~;
- [Demo](https://iamgio.eu/quarkdown/demo) for some useful snippets;
- [test](https://github.com/iamgio/quarkdown/tree/main/quarkdown-test/src/test/kotlin/com/quarkdown/test): this module tests the correct output of full Quarkdown programs, so you can find useful and complete examples here.
- [stdlib](https://github.com/iamgio/quarkdown/tree/main/quarkdown-stdlib/src/main/kotlin/com/quarkdown/stdlib): the whole codebase is fully documented, including the standard library, which is currently the only library available. It's not huge, so you can easily find all the available functions and their documentation from there;

Though it's obviously not the optimal solution, combining these resources will provide everything you need to use Quarkdown.

I'm keeping this issue open until the wiki reaches a better state. It won't cover *every* function from the stdlib though, as that would be quite inefficient. It is planned (not too soon though) to add a documentation-to-html exporter tool like many programming languages do.  

And (spoiler!) Quarkdown could get *'Documentation'* as a fourth document type, along with plain, slides and paged. This would allow to build the official documentation using Quarkdown itself - pretty cool heh.

That said, the GitHub wiki will expand and is going to be the main resource to learn Quarkdown from, at least for a while.

> PS: What about export to PDF?

It's planned too, however very far in the future. It's better to perfect the HTML experience before adding new targets. You can of course convert the HTML output to PDF via your browser.
- Paged documents are print-ready;
- Follow these [instructions](https://revealjs.com/pdf-export/) to losslessly save slides to PDF.

**Comment by iamgio** [comment]
Hi @lxwulf, it required more effort than expected, but I'm excited to announce the GitHub [wiki](https://github.com/iamgio/quarkdown/wiki) is now complete!

As of now, it covers a rough 90-95% of what Quarkdown has to offer, which is more than enough for most (if not all) users. I don't think I'll reach 100% though, which means mentioning every single minor function of the stdlib - I'd rather save that job for a future documentation generator tool.  
I will instead focus on more user-oriented guides, tutorials and possibly some behind-the-scenes articles which future contributors may find interesting.

Let me know if something in the wiki is not clear. Happy coding!

**Comment by lxwulf** [comment]
Hey @iamgio 👋,

At first, I want to excuse myself for being that late! I had a lot of things which flew around my ears. 🫨

I really appreciate your work, it looks very nice and detailed!

Of course, I will look into this! I'm still looking around for a good knowledge or documentation software where I can self define how the document looks but in a code like way, so I may create them automated and export them without restrictions to PDF (border ratio problem).

Anyway, again, many thanks to this and your future work in this Project! Maybe your Project will suit me needs. So or so I hope I can contribute to your Project in any way again in the future!

Also, I'm looking forward to your user-oriented guides! 👌

If something came up, I will say it. ✍️😊

Greets,

LxWulf 🐧🐺
